server:
  port: 8084

spring:
  application:
    name: oms-order-service

  datasource:
    url: jdbc:postgresql://localhost:5436/oms_order_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

services:
  product:
    url: http://localhost:8082
  inventory:
    url: http://localhost:8083

  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://sqs.us-east-1.localhost.localstack.cloud:4566

sqs:
  order-created-queue: order-created-queue
